#' Simulate a System Dynamics model
#'
#' @param ds_inputs A list of deSolve inputs generated by read_xmile
#' @param start_time A number
#' @param stop_time A number
#' @param timestep A number
#' @param integ_method A string. Either "euler" or "rk4"
#'
#' @return a data frame
#' @export
#'
#' @examples
#' path      <- system.file("models", "SIR.stmx", package = "readsdr")
#' ds_inputs <- xmile_to_deSolve(path)
#' sd_simulate(ds_inputs, 0, 1, 0.25, "rk4")
sd_simulate <- function(ds_inputs, start_time = NULL, stop_time = NULL,
                        timestep = NULL, integ_method = "euler") {

  if(!(integ_method %in% c("euler", "rk4"))) stop("Invalid integration method")

  if(is.null(start_time)) start_time  <- ds_inputs$sim_params$start
  if(is.null(stop_time))  stop_time   <- ds_inputs$sim_params$stop
  if(is.null(timestep))   timestep    <- ds_inputs$sim_params$dt

  # Create time vector
  simtime  <- seq(start_time, stop_time, by = timestep)

  ode_args <- list(y      = ds_inputs$stocks,
                   times  = simtime,
                   func   = ds_inputs$func,
                   parms  = ds_inputs$consts,
                   method = integ_method)



  if("graph_funs" %in% names(ds_inputs)) {
    ode_args$graph_funs <- ds_inputs$graph_funs
  }

  results <- do.call(deSolve::ode, ode_args)

  data.frame(results)
}

#' Perform a sensitivity run on a System Dynamics model
#'
#' @param consts_df
#' @param stocks_df
#'
#' @inheritParams sd_simulate
#'
#' @return A data frame
#' @export
#'
#' @examples
sd_sensitivity_run <- function(ds_inputs, consts_df = NULL, stocks_df = NULL,
                               start_time = NULL, stop_time = NULL,
                               timestep = NULL, integ_method = "euler") {

  if(!(integ_method %in% c("euler", "rk4"))) stop("Invalid integration method")

  if(is.null(start_time)) start_time  <- ds_inputs$sim_params$start
  if(is.null(stop_time))  stop_time   <- ds_inputs$sim_params$stop
  if(is.null(timestep))   timestep    <- ds_inputs$sim_params$dt

  # Create time vector
  simtime     <- seq(start_time, stop_time, by = timestep)

  ode_args <- list(y      = NULL,
                   times  = simtime,
                   func   = ds_inputs$func,
                   parms  = NULL,
                   method = integ_method)


  if(!is.null(consts_df)) {

    const_sensitivity_list <- do.call(function(...) Map(list,...), consts_df)

  }else {
    ode_args$parms <- ds_inputs$consts
  }


  if(!is.null(stocks_df)) {

    stock_sensitivity_list <- do.call(function(...) Map(list,...), stocks_df)

  } else {
    ode_args$y <- ds_inputs$stocks
  }

  #-----------------------------------------------------------------------------

  if(!is.null(consts_df) & is.null(stocks_df)) {
    iters   <- nrow(consts_df)
    df_list <- const_sensitivity(const_sensitivity_list, ode_args)
  }

  if(is.null(consts_df) & !is.null(stocks_df)) {
    iters   <- nrow(stocks_df)
    df_list <- stock_sensitivity(stock_sensitivity_list, ode_args)
  }

  if(!is.null(consts_df) & !is.null(stocks_df)) {
    row_consts <- nrow(consts_df)
    row_stocks <- nrow(stocks_df)

    if(row_consts != row_stocks) {
      stop("the number of rows in both data frames (consts & stocks) must be of equal size", call. = FALSE)
    }

    iters   <- nrow(consts_df)
    df_list <- const_stock_sensitivity(const_sensitivity_list,
                                       stock_sensitivity_list, ode_args)
  }

  sensitivity_df       <- do.call("rbind", df_list)
  sensitivity_df$iter  <- rep(1:iters, each = length(simtime))
  sensitivity_df
}

const_sensitivity <- function(const_sensitivity_list, ode_args) {
  df_list <- lapply(const_sensitivity_list, function(const_list) {
    ode_args$parms <- unlist(const_list)
    result_matrix  <- do.call(deSolve::ode, ode_args)
    data.frame(result_matrix)
  })
}

stock_sensitivity <- function(stock_sensitivity_list, ode_args) {
  df_list <- lapply(stock_sensitivity_list, function(stock_list) {
    ode_args$y     <- unlist(stock_list)
    result_matrix  <- do.call(deSolve::ode, ode_args)
    data.frame(result_matrix)
  })
}

const_stock_sensitivity <- function(const_sensitivity_list,
                                    stock_sensitivity_list, ode_args) {

  df_list <- purrr::map2(
    const_sensitivity_list, stock_sensitivity_list,
    function(const_list, stock_list) {

      ode_args$y     <- unlist(stock_list)
      ode_args$parms <- unlist(const_list)
      result_matrix  <- do.call(deSolve::ode, ode_args)
      data.frame(result_matrix)

    })
}
